server:
  port: 8801

spring:
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.44.99:5432/crux-scheduled-work
    username: postgres
    password: unitech
#  main:
#    allow-bean-definition-overriding: true
