server:
  port: 8801

spring:
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.53.129:5433/postgres
    username: postgres
    password: 111111
#  main:
#    allow-bean-definition-overriding: true
